#!/bin/bash

in=out/$1
out=$in"_alt"

mkdir -p $out

for f in `ls $in`
do

  echo $f
  convert $in/$f -canny 0x1+10%+20% $out/"$f".png
  convert $in/$f -canny 0x1+10%+20% -hough-lines 9x9+40 $out/"$f".mvg

done
